### PR TITLE
Change vagrant user to evap, test update_production backup.

### LINKED ISSUE #1240: Importing a backup made by update_production.sh does not work flawlessly.
Last week we wanted to do a production update. The json dump file created during that update could not be imported without issues:
- The dump does not contain the cronjob user, but foreign key references to it. This can not be imported
- The dump contains data included by django by default (auth, permission, ...). These need to be excluded when importing.

There should be some kind of documentation on what needs to be executed to import this dump back into the database. We should also add some test (could probably just run on travis) that ensures this always works (dump, flush database, migrate, load dump).

### PR DESCRIPTION
**Pull request by He3lixxx**
- [x] fixes #1240 (creates a restore_backup script and lets the process run once in travis)
- [x] for testing, creates an "evap" user in the vagrant vm and uses that. This is more similar to the production server (and necessary for testing update_production)

### CODE REVIEW

File: deployment/provision_vagrant_vm.sh [hunk 1]
```diff
@@ -21,16 +26,24 @@ apt-get -q install -y redis-server
 # install apache
 apt-get -q install -y apache2 apache2-dev
 
+# make user, create home folder, set uid 1000 (required for becoming the synced folder owner), set default shell to bash
+sudo useradd -m -u 1042 -s /bin/bash evap
+# allow ssh login
+sudo cp -r /home/vagrant/.ssh /home/$USER/.ssh
+sudo chown -R $USER:$USER /home/$USER/.ssh
+# allow sudo without password
+echo "evap ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/evap
```
Comment (He3lixxx) [inline deployment/provision_vagrant_vm.sh]: use $USER here

File: deployment/provision_vagrant_vm.sh [hunk 2]
```diff
@@ -21,16 +26,24 @@ apt-get -q install -y redis-server
 # install apache
 apt-get -q install -y apache2 apache2-dev
 
+# make user, create home folder, set uid 1000 (required for becoming the synced folder owner), set default shell to bash
```
Comment (karyon) [inline deployment/provision_vagrant_vm.sh]: replace "uid 1000" by "the same uid that's specified in Vagrantfile"?

**Comment by He3lixxx** [comment]
Alrighty, so I really really do not want to put any logic into the script that allows executing anything that might damage data without checking back with the user. For the reset_db and flush calls, this did not work out (tried to get it to for several hours), so now I fell back onto doing that by selectively passing `--noinput` to these calls. I don't like it, but I think it's better than not having a test.
@janno42 @karyon what do you think?

Test "logic" is in the .travis.yml, the part I don't like is the `ADDITIONAL_ARGUMENT` stuff in deployment/load_production_backup.sh

**Comment by He3lixxx** [comment]
Three points to think about:
- Currently we are backing up and importing back an empty database - do we want to have some meaningful data in it (At least the test finished very quick, although the TestDataTest is executed before)
- Currently, we are not asserting that the data that is imported back is actually what we expect, we only check whether the import script has exit code 0.
- We probably want to move the test "logic" into a proper test class, where it relies on subprocess.open or something similar, especially when we add more logic.

Any thoughts on this? For now, I'd ignore points 1 and 2 and only fix 3 (since this is the same we do with the load_data test and adding better assertions seems to be complex to me).

File: .travis.yml [hunk 3]
```diff
@@ -18,5 +19,9 @@ script:
   - python manage.py test --keepdb evap.evaluation.tests.test_misc.TestDataTest.load_test_data
   - python manage.py test --keepdb --reverse
   - python manage.py test --keepdb --debug-mode
+  # create a backup and load it again
+  - python manage.py migrate
+  - EVAP_OVERRIDE_BACKUP_FILENAME=true EVAP_SKIP_CHECKOUT=true EVAP_RUNNING_INSIDE_TRAVIS=true deployment/update_production.sh backup.json
```
Comment (karyon) [inline .travis.yml]: loaddata here?

File: Vagrantfile [hunk 4]
```diff
@@ -24,5 +24,13 @@ Vagrant.configure("2") do |config|
     #v.gui = true
   end
 
+  # override username to be evap instead of vagrant. Mounting with uid and gid is necessary as the provision script
```
Comment (karyon) [inline Vagrantfile]: and some comments on the "why" would be nice.

File: deployment/update_production.sh [hunk 5]
```diff
@@ -1,37 +1,56 @@
...
-if [ $# -eq 1 ] # if there is exactly one argument
-    then
-        echo Creating backup.
-        set -x # print executed commands. enable this here to not print the if above.
-        sudo -H -u evap env/bin/python manage.py dumpdata --indent 2 --output $1
-    else
-        echo No backup file specified, skipping backup creation.
-        set -x # print executed commands
-fi
+sudo -H -u $USERNAME $ENVDIR/bin/python manage.py dumpdata --natural-foreign --natural-primary --all -e contenttypes -e auth.Permission --indent 2 --output $FILENAME
```
Comment (karyon) [inline deployment/update_production.sh]: could you try putting that into dump_testdata?

Comment (He3lixxx) [reply deployment/update_production.sh]: It changes ID handling for the users: The users will not be referenced by id anymore but by username. The dump will not contain the old user id.

Comment (karyon) [reply deployment/update_production.sh]: hm, is that a problem?

Comment (He3lixxx) [reply deployment/update_production.sh]: Nope. Will add these parameters to the dump_testdata command.

File: .travis.yml (hunk 3 above)
Comment (He3lixxx) [reply .travis.yml]: added

File: Vagrantfile (hunk 4 above)
Comment (He3lixxx) [reply Vagrantfile]: added something, please check again.

**Comment by He3lixxx** [comment]
We thought about making these commands into management commands a bit more (as we thought it might be much better to test then), but we think there are two main points of failure:
- If these are managements commands, they are executed as the `evap` user. However, this user does not have sudo privileges. So, stuff like stopping and starting apache would not work. Additionally, checking out another commit and doing things like `pip install` while the manage.py file is running is somewhat smelly.
- If these are python files out of the management cycle, transactions in test cases get in our way. If, in a test case, we populate the database and then call any of these scripts, the test case transaction is still not committed, so the script will still see an empty database. This stops up from efficiently testing the scripts.

**Comment by karyon** [comment]
otherwise, lgtm!

**Comment by He3lixxx** [comment]
Does anyone else want to review this (@janno42?, @felixrindt?) Otherwise, I'd need an approval to be able to merge @karyon
